### ISSUE TITLE
UnicodeEncodeError:  codec can't encode character

### ISSUE THREAD

**Issue by theatischbein** [Debakel/feedDiasp#11]
I try to parse a twitter rss feed to diaspora. I've installed all dependencies but I still get an error

```
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 110: ordinal not in range(128)
```

The codec was changing from latin-1 to ascii by running multiple times.

Python version

```
root@localhost:~/feedDiasp# python -V
Python 2.7.3
```

used system

```
root@localhost:~/feedDiasp# uname -a
Linux localhost 3.2.0-4-amd64 #1 SMP Debian 3.2.73-2+deb7u2 x86_64 GNU/Linux
```

any idea how to fix this error ?

**Comment by Debakel** [comment]
https://github.com/Debakel/feedDiasp/commit/fa79a65c6ac82e9f78c5237a21cdcc61f8b7bd14 fixes this. Thanks @JonnyTischbein :)
