### ISSUE TITLE
What is this error about?

### ISSUE THREAD

**Issue by asterismo** [Debakel/feedDiasp#13]
espectador.py hs the feed information and user credentials

root@undernet:/usr/lib/python3/dist-packages/feedDiasp/feedDiasp# python3 espectador.py 
Traceback (most recent call last):
  File "espectador.py", line 1, in <module>
    from FeedDiasp import FeedDiasp
  File "/usr/lib/python3/dist-packages/feedDiasp/feedDiasp/FeedDiasp.py", line 61
    print 'Published: ' + post['title']
                      ^
SyntaxError: Missing parentheses in call to 'print'
root@undernet:/usr/lib/python3/dist-packages/feedDiasp/feedDiasp#

**Comment by Debakel** [comment]
It's not working with python3, use 2.7 instead: `python2.7 espectador.py`

I also recommend you to not run feedDiasp as root.
