### ISSUE TITLE
[BUG]: Termin:  {.field-label}

### ISSUE THREAD

**Issue by PolynomialDivision** [Debakel/feedDiasp#25]
Hi,
the field with the date looks like this:

Termin:  {.field-label}

![beispiel_bug](https://user-images.githubusercontent.com/10708466/28631244-da452402-722c-11e7-85a8-e9057adfb9c7.png)

**Comment by ghost** [comment]
+1 Same issue.

**Comment by ghost** [comment]
This is also related I think:

```
#<span>bot</span>{.mention
.hashtag}
```

It's from an atom feed

**Comment by ghost** [comment]
Fixed with changing line 50 in RSSParser.py:

`output = pypandoc.convert(text, 'md', format='html')`

to

`output = pypandoc.convert(text, 'plain', format='html')`
