### ISSUE TITLE
mrtz.me/feedDiasp does not accept all websites

### ISSUE THREAD

**Issue by manuels** [Debakel/feedDiasp#3]
There are some websites like `http://www.heise.de/tp/rss/news.rdf` or `http://blogsport.de/feed/` that are not accepted by the website: "Ungültiger Feed."
Could it be that the interface only allows `.rss` extensions?

**Comment by Debakel** [comment]
`http://www.heise.de/tp/rss/news.rdf` is not well-formed XML. It's declared as `us-asci`, but parsed as `utf-8`. That's why feedparser raises a bozo_exception [1].

We need another method of validating feeds.

[1] https://pythonhosted.org/feedparser/bozo.html#advanced-bozo

**Comment by manuels** [comment]
Interesting, I'm gonna have a closer look at the feedparser

**Comment by manuels** [comment]
Maybe this helps: https://pythonhosted.org/feedparser/character-encoding.html#handling-incorrectly-declared-media-types
