### ISSUE TITLE
feedDiasp does not login to 0.5.0.0?

### ISSUE THREAD

**Issue by silberzwiebel** [Debakel/feedDiasp#5]
Hi,

I've tried to run feedDiasp with my raspberry pi, but it fails to login:

```
Failed to login: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "__init__.py", line 24, in <module>
    bot.publish()
  File "/home/pi/diaspora-proasyl/feedDiasp/feedDiasp/FeedDiasp.py", line 52, in publish
    self.diasp.login()
  File "/home/pi/diaspora-proasyl/feedDiasp/feedDiasp/Diasp.py", line 20, in login
    raise LoginException(str(e))
feedDiasp.Diasp.LoginException: 'NoneType' object has no attribute 'group'
```

Looking at https://diasp.eu/tags/botpost it seems that only bots at diasp.org are still publishing. And diasp.org has still version 0.4.0.3.

Could you fix this? Or tell me what I might do wrong?

Thanks, silberzwiebel

**Comment by Debakel** [comment]
Hi, please update the submodules to get the newest version of _diaspy_:
`git submodule init`
`git submodule foreach git pull origin master`

**Comment by silberzwiebel** [comment]
Alright, it works now. Using http://diasp.eu, however, does not work. One has to use https://diasp.eu

Thanks
