### ISSUE TITLE
html code gets posted to diaspora

### ISSUE THREAD

**Issue by schiessle** [Debakel/feedDiasp#7]
If the rss feed contain html code the code gets posted to diaspora verbatim. Seems like Diaspora doesn't interpret HTML code as part of the post or that feedDiasp escape it in a way that Dispora post it verdatim.

**Comment by Debakel** [comment]
Commit https://github.com/Debakel/feedDiasp/commit/76477ae8418f6a757a94c913f7e2ba6aa92d757b should solve this.

**Comment by ghost** [comment]
@Debakel Do you still maintain this repository? 

HTML is still (or again) posted on Diaspora. Odd thing is, that it only goes wrong in the desktop web-app.

This is in the .atom feed:

`&lt;a href="https://www.globalinfo.nl/Nieuws/10-februari-grote-manifestatie-zad" rel="nofollow noopener" target="_blank"&gt;&lt;span class="invisible"&gt;https://www.&lt;/span&gt;&lt;span class="ellipsis"&gt;globalinfo.nl/Nieuws/10-februa&lt;/span&gt;&lt;span class="invisible"&gt;ri-grote-manifestatie-zad&lt;/span&gt;&lt;/a&gt;`

And this is displayed in the Diaspora web-app (but correctly linked):

`<span class="invisible">https://www.</span><span class="ellipsis">globalinfo.nl/Nieuws/10-februa</span><span class="invisible">ri-grote-manifestatie-zad</span>`

HTML source: `<a href="https://www.globalinfo.nl/Nieuws/10-februari-grote-manifestatie-zad" target="_blank" rel="noopener noreferrer">&lt;span class="invisible"&gt;https://www.&lt;/span&gt;&lt;span
class="ellipsis"&gt;globalinfo.nl/Nieuws/10-februa&lt;/span&gt;&lt;span
class="invisible"&gt;ri-grote-manifestatie-zad&lt;/span&gt;</a>`

All module dependencies are installed (Debian 9).

**Comment by ghost** [comment]
Fixed with changing line 50 in RSSParser.py:

`output = pypandoc.convert(text, 'md', format='html')`

to

`output = pypandoc.convert(text, 'plain', format='html')`
