### ISSUE TITLE
not able to login after diaspora* upgrade (I guess)

### ISSUE THREAD

**Issue by ghost** [Debakel/feedDiasp#8]
Hi,

My setup was perfectly fine until 5 days ago when it stopped working with the following error:

> $ ./submit.py 
> Login as journalduhacker to https://framasphere.org
> Failed to login: 404: could not fetch data for post: a7d68de06b5101334a422a0000053625
> Traceback (most recent call last):
>   File "./submit.py", line 9, in <module>
>    bot.publish()
>   File "/home/chaica/retweets/feedDiasp/feedDiasp/FeedDiasp.py", line 52, in publish
>     self.diasp.login()
>   File "/home/chaica/retweets/feedDiasp/feedDiasp/Diasp.py", line 23, in login
>     raise LoginException(str(e))
> feedDiasp.Diasp.LoginException: 404: could not fetch data for post: > a7d68de06b5101334a422a0000053625

Diaspora\* version is 0.5.4.0-p667f4e4c

Regards,
Carl

**Comment by ghost** [comment]
Hi,

any news about this issue? I would be delighted to help to reproduce it if you could not.

**Comment by Debakel** [comment]
Hi Carl,

this seems to be a known bug in `diaspy`: https://github.com/marekjm/diaspy/issues/27 (and https://github.com/marekjm/diaspy/issues/23)
